---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_ingress_type: Ingress
  tower_hostname: awx.example.com
  tower_image: quay.io/ansible/awx:18.0.0
  tower_ee_images:
    - name: awx-ee
      image: quay.io/ansible/awx-ee:0.2.0
